default: &default
  adapter: postgresql
  encoding: unicode
  #pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #template: template0
  host: localhost
  username: "pragati"
  password: "admin"

development:
  <<: *default
  database: cart_development

test: &TEST
  <<: *default
  database: cart_test

production:
  <<: *default
  database: cart_production
